### ISSUE TITLE
[BUG] - Modal doesn't show scrollbar under certain pre conditions

### ISSUE THREAD

**Issue by stephanschroeter** [porsche-design-system/porsche-design-system#3509] opened 2024-09-25 09:03 UTC
### JS Framework

All

### Porsche Design System version

3.18.0

### On which device(s) you can see the bug?

MacBook Pro

### In which browsers you can see the bug?

Firefox, Chrome

### Reproduction Example

https://porschedev.slack.com/archives/CT7AVHTTQ/p1726656935319749

### Steps to reproduce the behavior

1. Go to OS settings and activate "show scrollbars always"
2. Go to https://moduleguide.pcom.weu.porsche.com/__sandbox.html?storyId=src-modules-features-features-story-vue&variantId=src-modules-features-features-story-vue-0
3. Click on 'open drawer'
4. See error, Modal doesn't show any scrollbar in Chrome or Firefox while Safari works

<img width="1665" alt="Screenshot 2024-09-25 at 10 54 02" src="https://github.com/user-attachments/assets/64e792f9-503c-4390-8249-00fe6f6832d1">

### Expected behavior

Modal shall show scrollbar correctly in Chrome and Firefox

**Comment by kaiszybiak** [comment] 2024-09-30 09:50
Closing this issue:

After further investigation, we identified that the issue is related to a known Chrome bug: [[Issue 40835364](https://issues.chromium.org/issues/40835364) - `scrollbar-gutter` hides the scrollbar of fixed containers].

See Slack conversation: https://porschedev.slack.com/archives/CT7AVHTTQ/p1727688242279909?thread_ts=1726656935.319749&cid=CT7AVHTTQ

**Closed by kaiszybiak** 2024-09-30 09:50 UTC
Labels: bug, to be refined, community
