### ISSUE TITLE
Use new <dialog> component / inert attribute

### ISSUE THREAD

**Issue by SetupCoding** [porsche-design-system/porsche-design-system#2076] opened 2022-09-29 14:15 UTC
Scope
---

Our current Modal has workarounds in place to support the correct focus behaviour.
Alternatively we could implement the `intert` attribute or `dialog` Element to provide future proof features.

Article https://web.dev/building-a-dialog-component/

https://caniuse.com/?search=inert
https://caniuse.com/?search=dialog

Out of Scope
---
List topics that are not part of this task.

Notes  
---
- Related: #2285

Acceptance criteria
---
- [ ] Criteria

Subtasks
---
- [ ] Task

**Comment by o-hook** [comment] 2024-01-15 13:26
duplicate of #2682

**Closed by o-hook** 2024-01-15 13:26 UTC
Labels: component, to be refined, code, browser compatibility
