### ISSUE TITLE
[BUG] - PCarousel component prints a warning when renders in the unit tests

### ISSUE THREAD

**Issue by alexzelenuyk** [porsche-design-system/porsche-design-system#2917] opened 2023-12-04 14:33 UTC
### Contact Details

net.oleksii.zeleniuk@mhp.com

### JS Framework

Next.js

### Porsche Design System version

3.9.0

### Reproduction Example

When running unit tests

### Steps to reproduce the behavior

1. Take an example, like https://designsystem.porsche.com/v3/components/carousel/examples#jump-to-slide-active-slide-index
2. Create a test: 
```
import {render} from '@testing-library/react';

render(<Component/>);
...
```

### Expected behavior

No warnings

### Relevant log output

```shell
console.error
    Warning: Each child in a list should have a unique "key" prop.
    
    Check the render method of `DSRCarousel`. See https://reactjs.org/link/warning-keys for more information.
```
```

**Comment by denyo** [comment] 2024-01-30 13:43
Duplicate of #2990 which was addressed in #3001.

**Closed by denyo** 2024-01-30 13:43 UTC
Labels: to be refined
