### ISSUE TITLE
[BUG] Flyout isn't full width on mobile

### ISSUE THREAD

**Issue by denyo** [porsche-design-system/porsche-design-system#2626] opened 2023-06-26 13:08 UTC
### Contact Details

Alexander Dreymann

### JS Framework

Next.js but probably all

### Porsche Design System version

3.2

### Reproduction Example

https://b2b-configurator-1powv4qit-alexdreymannpdg.vercel.app/ca/29480151782409668270199290480225

### Steps to reproduce the behavior

1. Go to https://b2b-configurator-1powv4qit-alexdreymannpdg.vercel.app/ca/29480151782409668270199290480225
2. Click on first `p-button-pure`
3. See `p-flyout` open
4. Resize browser to mobile
5. See weird gap with backdrop on left side

<img width="521" alt="Bildschirmfoto 2023-06-26 um 14 59 15" src="https://github.com/porsche-design-system/porsche-design-system/assets/4380295/9e4a7f8e-1510-43cd-8277-c45f34a9b09c">

![Image](https://github.com/porsche-design-system/porsche-design-system/assets/30120450/4dad6df4-f371-4195-8edb-307cf0894503)

### Expected behavior

No gap on mobile, should be full-width.

**Comment by henrijoss** [comment] 2023-07-11 12:38
The Flyout scales with the content inside. The content is set to width: 80vw, so this is intended behavior.

**Comment by stephanschroeter** [comment] 2023-07-18 12:28
Won't fix, due to bad integration, see screenshot:

![Image](https://github.com/porsche-design-system/porsche-design-system/assets/30120450/5acc5e13-db7f-4078-99b6-8e2b31110061)

**Closed by stephanschroeter** 2023-07-18 12:28 UTC
Labels: bug, component, to be refined, community
