### ISSUE TITLE
Move fonts, marque, email, icons, meta-icons into assets as sub project

### ISSUE THREAD

**Issue by stephanschroeter** [porsche-design-system/porsche-design-system#1848] opened 2022-04-13 10:41 UTC
Scope
---
Describe clearly the scope of the task.

Out of Scope
---
List topics that are not part of this task.

Notes  
---
Share any further information that is relevant for processing.

Acceptance criteria
---
- [ ] Criteria

Subtasks
---
- [ ] Task

**Comment by denyo** [comment] 2023-11-29 12:50
Duplicate of #2709

**Closed by denyo** 2023-11-29 12:50 UTC
Labels: to be refined, code, to be written
